# ------------------------------------------------------------------------------
# iron proxy server configuration
server:
  host: 0.0.0.0
  port: 8080
  redis_url: redis://iron-x-iris-redis:6379
  client_max_size: 104857600
# ------------------------------------------------------------------------------
# iron proxy storage configuration
storage:
  directory: /data/storage
# ------------------------------------------------------------------------------
# fusion auth api configuration
auth_api:
  backend:
    strategy: basic
    basic:
      groups: []
      users: []
  clients: []
  iron_key: null
  can_delete_acs: []
# ------------------------------------------------------------------------------
# fusion case api configuration
case_api: {}
# ------------------------------------------------------------------------------
# fusion info api configuration
info_api:
  auth_required: false
# ------------------------------------------------------------------------------
# iron proxy dfir iris client configuration
iris_client:
  api_url: https://iris.domain.lan/
  api_key: api-key-placeholder
  api_ssl: false
  api_as_admin: true
  unmanaged_uids: [1]
  case_customer_id: 1
  case_template_id: null
  case_classification_id: null
  update_case_acs: true
  update_case_summary: true
  append_case_custom_attributes: true
